accent = "#95abb6"
cursor = "#11262e"
foreground = "#718791"
background = "#2f444d"
selection_foreground = "#95abb6"
selection_background = "#586d77"

color0 = "#95abb6"
color1 = "#7BA1B5"
color2 = "#6C838E"
color3 = "#66808C"
color4 = "#536972"
color5 = "#3F5056"
color6 = "#6B8791"
color7 = "#7C9DA8"
color8 = "#91B7C4"
color9 = "#7A9AA5"
color10 = "#8D9DA3"
color11 = "#7294A0"
color12 = "#566F77"
color13 = "#91A1A5"
color14 = "#7C9BA3"
color15 = "#3A6B77"
