# Background and foreground colors
background = #232829
foreground = #d6dbdc

# Standard colors
palette = 0=#232829
palette = 1=#94abb8
palette = 2=#98b3aa
palette = 3=#98b3b0
palette = 4=#95abb6
palette = 5=#97aab4
palette = 6=#b0c0c5
palette = 7=#d6dadc

# Bright colors
palette = 8=#788487
palette = 9=#93aab8
palette = 10=#98b3a6
palette = 11=#98b3b3
palette = 12=#94abb8
palette = 13=#96abb6
palette = 14=#e5eaec
palette = 15=#d6dbdc
