# =========================
# Kitty Terminal Colors
# =========================

# Background and Foreground
background            #232829
foreground            #d6dbdc
cursor                #d6dbdc
selection_background  #788487
selection_foreground  #232829

# =========================
# Normal Colors
# =========================
color0   #232829
color1   #94abb8
color2   #98b3aa
color3   #98b3b0
color4   #95abb6
color5   #97aab4
color6   #b0c0c5
color7   #d6dadc

# =========================
# Bright Colors
# =========================
color8   #788487
color9   #93aab8
color10  #98b3a6
color11  #98b3b3
color12  #94abb8
color13  #96abb6
color14  #e5eaec
color15  #d6dbdc

# =========================
# Borders
# =========================
active_border_color     #d6dbdc
inactive_border_color   #788487
bell_border_color       #94abb8

# =========================
# Cursor Trail
# =========================
cursor_trail 1